#!/bin/sh -e

# if test -n "$(git status --porcelain)"
# then
#     echo 'git repo is dirty, clean up before tagging'
#     exit 1
# fi

if test -z "$1"
then
    echo 'specify the release version (ex. 1.0.0)'
    exit 1
fi

echo "Releasing $1"

sd "\* Version:           \S+" "* Version:           $1" woocommerce-net-terms.php
sd "NET_TERMS_CURRENT_VERSION', '(\S+)'" "NET_TERMS_CURRENT_VERSION\', \'$1\'" woocommerce-net-terms.php
# update plugin version
# commit
# tag

rm -f woocommerce-net-terms.zip
zip -r woocommerce-net-terms.zip LICENSE *.php includes/*
# hub release create

# update data.json version, last_updated, download_link
# commit
# deploy-function?

# ./scripts/deploy-function
